# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0f7ea03c9683369fc262ad9ce75c85eb7c8e62502a1c15191defdc35e79cf6e101a94075c48556665b9af058f49eb3f26900fb868e169df45f22e99f2d33dccc

test:
  secret_key_base: 668b9d95f43a61b99e11f616d3b6823e3c13561df08a461d59117fa25c9ce78e56c62a49d899496388d2cb48f2e954e9d4f1488ff18c6f05c551c27d459031f7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
